services:
    - type: web
      name: bhh-api
      runtime: docker
      region: singapore
      plan: free
      healthCheckPath: /actuator/health
      envVars:
          - key: SPRING_PROFILES_ACTIVE
            value: prod
          - key: SPRING_DATASOURCE_URL
            sync: false
          - key: SPRING_DATASOURCE_USERNAME
            sync: false
          - key: SPRING_DATASOURCE_PASSWORD
            sync: false
