services:
    - type: web
      name: bhh-api
      runtime: docker
      region: singapore
      plan: free
      healthCheckPath: /actuator/health
      envVars:
          - key: SPRING_DATASOURCE_URL
            fromDatabase:
                name: bhh-web-db
                property: connectionString
          - key: SPRING_DATASOURCE_USERNAME
            fromDatabase:
                name: bhh-web-db
                property: user
          - key: SPRING_DATASOURCE_PASSWORD
            fromDatabase:
                name: bhh-web-db
                property: password
